name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

        # Install Node.js on the runner
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

        # Install project dependencies
      - name: Install Dependencies
        run: npm install

        # Start the Node.js application in the background
      - name: Start Node.js Application
        run: |

          npm run dev &

        # Wait for the application to be fully up and running
      - name: Wait for Application to Start
        run: |
          while ! curl -s http://localhost:3000/movies > /dev/null; do
            echo "Waiting for application to start..."
            sleep 2
          done

      - name: Running Test Scenario
        run: npm run apidog
